### ISSUE TITLE
Unable to connect to Emerald Services.

### ISSUE THREAD

**Issue by whichouno** [emeraldpay/emerald-wallet#1050]
Emerald Wallet Version: 2.1.2

every time i launch emerald wallet on my mac, the app show "Unable to connect to Emerald Services. Please check your Internet connection", even if i switch networks.

**Comment by splix** [comment]
Hi @whichouno, thank you for reporting the problem. Is there any specifics about your internet connection that we should know? For example we're aware about the problems connecting from China, and hope to improve it at some point.

**Comment by Nick839** [comment]
I'm in North America is it just the influx of trade that's causes the Emerald Wallet to be having this connection error. i have a 33ms second to the  network not reason to have a connection issue
