### ISSUE TITLE
Blank Screen on Sending depostis 2.1.2

### ISSUE THREAD

**Issue by aptpupil303** [emeraldpay/emerald-wallet#1056]
When I attempt to send a deposit I get a white screen and then a Java error appears after several minutes. 
![sending](https://user-images.githubusercontent.com/48875083/73671587-14eb6f80-4660-11ea-85c4-38dd9e4851c5.PNG)

**Comment by aptpupil303** [comment]
This was using windows 10 1903

**Comment by brancocu** [comment]
Hola amigo me puedes ayudar me pasa exactamente lo mismo intento hacer un envio y no medeja me queda la pantalla en blanco que esta pasando ? es primera vez que ocupo emerald wllet y ya no funciona :( me estafaron? amigo alguna ayuda que puedo hacer en este caso porfavor alguien alguna solucion?

**Comment by splix** [comment]
Can you please try just released version v2.1.4 - https://github.com/emeraldpay/emerald-wallet/releases/tag/v2.1.4

**Comment by brancocu** [comment]
Yeah man I used version 2.1.3 and I can transfer ok no buy anymore etc a
real shit xd jajaja

**Comment by brancocu** [comment]
Hola emeraldpay/emerald-wallet,
Tienes un mensaje de Branco Benavides en IQ Elite para ti. 
Haz click aqui https://a.iqelite.com/j/KOZIrb/agp/ para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: https://a.iqelite.com/common/unsubscribe/?code=6c452430&email=reply@reply.github.com. IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------

**Comment by brancocu** [comment]
Bonjour,

Branco  vient de s'inscrire sur IQ Elite. Il vous a écrit un message. 

Pour lire ce message avant qu'il n'expire, il suffit de cliquer sur le lien suivant : https://a.iqelite.com/entry/new_message/2b120aa04b80bb0c604aa3ce1bec626c2d3fda9e1f544b80bfb/320c612f7502faa0c19eff5746f12b0b81183e20c4b506f345f83e76f3b6ef04b27b7f6c63cb104dadab7b83cccf57ce0c320c612f75044d3e22edb35af44b80bfb/

Lisez votre message avant qu'il ne disparaisse !            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : https://a.iqelite.com/common/unsubscribe/?code=6c452430&email=reply@reply.github.com.
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by brancocu** [comment]
Bonjour,

Votre ami Branco vous a envoyé un message il y a 36h jours, mais vous ne l'avez toujours pas lu. 

Le message sera supprimé dans 24 heures. 

Pour savoir ce que Branco vous a écrit, cliquez ici : https://a.iqelite.com/entry/new_message/2b120aa04b80bb0c604aa3ce1bec626c2d3fda9e1f544b80bfb/320c612f7502faa0c19eff5746f12b0b81183e20c4b506f345f83e76f3b6ef04b27b7f6c63cb104dadab7b83cccf57ce0c320c612f75044d3e22edb35af44b80bfb/            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : https://a.iqelite.com/common/unsubscribe/?code=6c452430&email=reply@reply.github.com.
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by brancocu** [comment]
Hola emeraldpay/emerald-wallet,


Tienes un mensaje de Branco Benavides en IQ Elite para ti. 


Haz click aqui https://a.iqelite.com/j/KOZIrb/agp/ para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: https://a.iqelite.com/common/unsubscribe/?code=6c452430&email=reply@reply.github.com. IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
