### ISSUE TITLE
White screen when sending ETC on 2.1.2

### ISSUE THREAD

**Issue by kbirken** [emeraldpay/emerald-wallet#1057]
I am using Emerald Wallet 2.1.2 on a Mac with macOS Catalina 10.15.3. When signing s Send transaction, I get a white screen with no progress. The transaction is not executed. Here is what the console says:

![image](https://user-images.githubusercontent.com/1193045/73731427-c231b680-4738-11ea-95ea-e70248567fd1.png)

Doesn't look right...

**Comment by brancocu** [comment]
Hola muy buenas tardes me pasa exactamente lo mismo intento enviar una cantidad de 6 etc a una billetera binance y la pantalla de mi pagina queda en blanco que esta pasando ? esta mi dinero quiero saber cual es la solucion amigos porfavor alguien ??

**Comment by kbirken** [comment]
Here is the English (machine-)translation of the previous comment: 

> Hello very good afternoon I try to send an amount of 6 etc to a binance wallet and the screen of my page is blank what is happening ? is my money I want to know what is the solution friends please someone ?

**Comment by splix** [comment]
Can you please try just released version v2.1.4 - https://github.com/emeraldpay/emerald-wallet/releases/tag/v2.1.4
