### ISSUE TITLE
Unable to connect to Emerald Services

### ISSUE THREAD

**Issue by Mikle-K** [emeraldpay/emerald-wallet#1119]
Hello. Just today I have an issue to connect to Emerald Wallet. I've got message: "Unable to connect to Emerald Services. Please check your Internet connection". But my internet connection works just fine. Is there any problem with connection to Emerald service server (May be Emerald IP's blocked by my internet provider for example)?  How could I check this?

**Comment by StanlyShauro** [comment]
The same problem.

**Comment by splix** [comment]
It seems that you're using an old version of the Emerald Wallet, which had connectivity issues. Please make sure you use the latest version, which you can download at https://emerald.cash/download/

**Comment by Mikle-K** [comment]
I am using new version 2.4.2. But now Emerald wallet works fine. Don't know, what thing may cause this issue earlier...

**Comment by splix** [comment]
Sorry, it wasn't because of the app. We had a technical issue with the servers, in fact, which is fixed now. Everything should be working fine now.
