### ISSUE TITLE
Deposit failed

### ISSUE THREAD

**Issue by Guo888abc** [emeraldpay/emerald-wallet#1131]
Dear all,

I occurred an issue with my emerald wallet. Tried to bridge my USDT from my BSC wallet to yuzuswap. However, the coins are not recognized in the swap function. Then I transferred those USDT back to my Binance. However, it was lost. I am so comfused. Checked with Binance but they can't find my transition. Here is my Transition hash: 0x1424169d9b9870a6593eefb83eadd5523f4c4de87a8d6e1b1ddd8556486549c4

Can anyone help to have a look at what was going on??? Feel helpless. 

TIA

**Comment by Guo888abc** [comment]
Follow-up with the original issue, I've checked with a Supporter from Binance. They help to check and it didn't get into their chain. Could Emerald wallet team help me to check where are my coins? Thank you a lot.

**Comment by splix** [comment]
Hi @Guo888abc! Thank you for reaching out to us out. It's not very clear what kind of problem you have and how Emerald Wallet is related. You said it's about BSC and Yuzuswap, but we don't have any support for those networks. Emerald supports only Bitcoin, Ethereum, and Ethereum Classic.
If you're sure you have used Emerald Wallet and are having this problem, please raise a support ticket here: https://emerald.cash/support.

Thank you.
