### ISSUE TITLE
Stuck on startup when upgrading from 0.9 to 0.10

### ISSUE THREAD

**Issue by pyskell** [emeraldpay/emerald-wallet#571]
Emerald Wallet gets stuck here:

![image](https://user-images.githubusercontent.com/9665963/39709805-e34ce0f2-51e8-11e8-810d-c556b58874a6.png)

The temporary fix is to click to the right of the monitor icon and select a node.

**Comment by shanejonas** [comment]
can you clear your settings by following this: https://github.com/ETCDEVTeam/emerald-wallet#troubleshooting

let me know if a fresh start fixes it

**Comment by pyskell** [comment]
Yup, that also fixes it
