### ISSUE TITLE
Doesn't launch emerald vault

### ISSUE THREAD

**Issue by splix** [emeraldpay/emerald-wallet#819]
Build [16897d9] for Macos, fresh install. 

Nothing in logs, just a fetch error when it tries to create a first account.

**Comment by BelfordZ** [comment]
After uninstalling, and reinstalling, Im not able to reproduce this.

Were you running vault in the BG before starting the wallet?

**Comment by splix** [comment]
hm, where emerald binary is located then? I just see that for a previous installation it was in `bin`

**Comment by splix** [comment]
I don't see emerald vault in Activity Monitor too

**Comment by BelfordZ** [comment]
AH okay, I got it reproduced now. Thanks :)
